### PR TITLE
Update README with Google Play Store link and formatting

### PR DESCRIPTION
**Pull request by JW-CH**

### CODE REVIEW

**Comment by 3rob3** [comment]
Looks good! Need to wait to pull though, publish got rejected by Google for icon sizes, and also they want me to provide them with credentials for testing. WTF? Like they have reviewed it 5 times already and now at the final step they pull this.

**Comment by JW-CH** [comment]
> Looks good! Need to wait to pull though, publish got rejected by Google for icon sizes, and also they want me to provide them with credentials for testing. WTF? Like they have reviewed it 5 times already and now at the final step they pull this.

Just give them the link to the https://demo.immich.app/ instance. idk haha

**Comment by 3rob3** [comment]
> > Looks good! Need to wait to pull though, publish got rejected by Google for icon sizes, and also they want me to provide them with credentials for testing. WTF? Like they have reviewed it 5 times already and now at the final step they pull this.
> 
> Just give them the link to the https://demo.immich.app/ instance. idk haha

I thought about that. They provide the login credentials but no API key:
username - demo.immich.app
password -demo
I guess I could ask Alex if they can provide it.

**Comment by 3rob3** [comment]
> Woah, hold on a minute. The Play Store link you have is just a link, Google prefers you have a Get it on Google Play button that is a link and it needs to be compliant if you do.
> 
> https://partnermarketinghub.withgoogle.com/brands/google-play/visual-identity/badge-guidelines/

After the PITA it was to get it approved, I really don't care what they prefer.

**Comment by NicholasFlamy** [comment]
> > Woah, hold on a minute. The Play Store link you have is just a link, Google prefers you have a Get it on Google Play button that is a link and it needs to be compliant if you do.
> > https://partnermarketinghub.withgoogle.com/brands/google-play/visual-identity/badge-guidelines/
> 
> After the PITA it was to get it approved, I really don't care what they prefer.

They make everything a PITA. I'm just putting it here because I don't know if they would demand you have it.

**Pull request merged**
