### PR TITLE
Change SettingsView Int fields to NumericUpDown

### PR DESCRIPTION
**Pull request by 3rob3**
Change SettingsView Int fields to NumericUpDown

### CODE REVIEW

**Comment by 3rob3** [comment]
Navigating these fields on Android was a pain, this helps.

**Comment by JW-CH** [comment]
Your formatting seems off again. Could you double check?

**Comment by 3rob3** [comment]
> Your formatting seems off again. Could you double check?

Ugh, this is annoying…yeah I will check. Thanks for reviewing. If you ever want me to stop requesting just let me know.

**Comment by 3rob3** [comment]
> Your formatting seems off again. Could you double check?

Yeah, so that one was my fault. Fixed (I f'ing hope)

**Comment by JW-CH** [comment]
The formatting still seems off. How do you auto-format the code? I am using Visual Studio 2022 with the shortcut Ctrl+k, Ctrl+d

**Comment by 3rob3** [comment]
Edit-Advanced-Format Document. Really stupid that doesn't do the same thing.

**Comment by JW-CH** [comment]
> Edit-Advanced-Format Document. Really stupid that doesn't do the same thing.

It does the same thing. (Or at least it should)

What version of VS are you using? Should I create a commit how it formats it for me?

**Comment by 3rob3** [comment]
> > Edit-Advanced-Format Document. Really stupid that doesn't do the same thing.
> 
> It does the same thing. (Or at least it should)
> 
> What version of VS are you using? Should I create a commit how it formats it for me?

It apparently does, because it changed when I did the keyboard shortcuts. I pushed that change so it should be right now.
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.6

**Pull request merged**
