### PR TITLE
Add image stretch options Closes #103

### LINKED ISSUE #103: Configure scaling method (scale to fit vs. cover)
### Description

Users should be able to controll whether pictures that doesn't have the same ratio as the screen are scaled down to fit (+ that nice blur background effect) or if they should be scaled up to cover the full screen.

### Use Case

Picuter and Display have different ratio. (e.g. 4:3 vs. 16:9)

### Details

_No response_

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

### PR DESCRIPTION
**Pull request by 3rob3**
Closes #103

### CODE REVIEW

**Comment by ScottFries** [comment]
Started playing with this to see how `  "ImageStretch": "Fill"` would look in my use-case, but can't seem to get this setting to be honored regardless of which setting I use. I tried digging in to why this might be, but my dated knowledge of AXAML is gating me.
Is someone else able to confirm if this setting is working as intended?

**Comment by 3rob3** [comment]
What platform are you on? Android doesn’t seem to be honoring it, no clue why yet.

**Comment by ScottFries** [comment]
Desktop (Windows, haven't tried Linux yet).
And I'll likely be leaving it at Uniform; I was just curious to see how bad Fill looks sunce most of my images would only have a small stretch applied.

**Comment by 3rob3** [comment]
Hmm, that’s strange. It works perfect for me on Windows but not Android. Maybe that’s a clue. I will investigate more after work.

**Comment by 3rob3** [comment]
> Started playing with this to see how ` "ImageStretch": "Fill"` would look in my use-case, but can't seem to get this setting to be honored regardless of which setting I use. I tried digging in to why this might be, but my dated knowledge of AXAML is gating me. Is someone else able to confirm if this setting is working as intended?

Try it again. Should be working now.

**Comment by ScottFries** [comment]
> UniformToFill

Works perfect; thanks!

**Comment by bballdavis** [comment]
I was looking to use this enhancement, but its seems to have been removed.  Are there plans to add this back into the refactored stack?

**Comment by 3rob3** [comment]
Not currently, with splitview and image zooming options it doesn't really feel necessary. But feel free to submit a new request if you feel differently :).

**Pull request merged**
