### PR TITLE
- Highlight required settings with red border (if blank). - Avalonia update

### PR DESCRIPTION
**Pull request by 3rob3**

### CODE REVIEW

**Comment by 3rob3** [comment]
What do you guys think of this. If Immich URL or API key are blank they will be highlighted red. Looks like this:
image

**Comment by ScottFries** [comment]
> What do you guys think of this. If Immich URL or API key are blank they will be highlighted red. Looks like this: image @ScottFries

Seems like a nice clarifying improvement to UX!

**Comment by JW-CH** [comment]
I like the highlighting, but I don't like that nothing really happens. It is red but still lets you save corrupt/invalid settings.

**Comment by 3rob3** [comment]
> I like the highlighting, but I don't like that nothing really happens. It is red but still lets you save corrupt/invalid settings.

updated.

**Pull request merged**
